<html><head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
<!-- A minimal Flowplayer setup to get you started -->
  

	<!-- 
		include flowplayer JavaScript file that does  
		Flash embedding and provides the Flowplayer API.
	-->
	<script type="text/javascript" src="/js/jquery-1.2.6.min.js"></script>
	<script type="text/javascript" src="/js/flowplayer-3.1.4.min.js"></script>
	

	
	<!-- page title -->
	<title>Captions Plugin with Timed Text</title>

</head><body>

	<div id="page">
		
		<h1>Captions Plugin with Timed Text</h1>
		
		<p></p>

		<!-- this A tag is where your Flowplayer will be placed. it can be anywhere -->
		<a  
			 href=""  
			 style="display:block;width:400px;height:300px"  
			 id="captions"> 
		</a> 
		
	
		<!-- this will install flowplayer inside previous A- tag. -->

		
		<script>
		$f("captions", {src:"/swf/flowplayer.swf",bgcolor:'#000000'}, {

			playlist: [
	
				// 1:st clip
				{
					url: 'KimAronson-TwentySeconds73213.flv'
				},
				
			], 
			clip: {
				baseUrl: 'http://blip.tv/file/get/',
				//provider: 'rtmp',
				autoPlay: false,
				onStart: function(clip)  {
			
				}
			}, 
			
			log:  {         
			     
				     // other levels are: 'info', 'warning', 'error' which will cause less output 
				     level: 'debug',
				     filter: 'org.flowplayer.shareembed.*, org.flowplayer.rtmp.*' 
				},
			plugins:  {
				rtmp: {
					 url: '/swf/flowplayer.rtmp.swf',
					 netConnectionUrl: 'rtmp://cyzy7r959.rtmphost.com/flowplayer',
					 objectEncoding: 0
     				 
				},
				share: {
					url:'/swf/flowplayer.shareembed.swf',
					emailScriptURL: "http://embed.electrocode.net/email",
                    emailScriptToken: "<?=$this->emailToken;?>",
					emailSubject: "Video you might be interested in",
					style: {
	                    'body': {
	                    fontSize: '14',
	                    fontFamily: 'Arial',
	                    textAlign: 'center',
	                            color: '#ffffff'
	                            //backgroundColor:'#000000'
	                    }
	                }
				}
			},
		
		
		});
		
		function closerelated(btn)
     	{
     		$f().getPlugin("related").close();
     	}
     	
     	function show(btn)
     	{
     		$f().getPlugin("related").show();
     	}
     	
     	function openrelated(btn)
     	{
     		$f().getPlugin("related").open();
     	}
     	
		//}}}
		</script>
		
		<a href="#" onclick="openrelated();">Open</a> &nbsp; <a href="#" onclick="closerelated();">Close</a> &nbsp; <a href="#" onclick="show();">Show</a>
		
		
	</div>
	
	
</body></html>